//go:build linux

package main

import (
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

// TestRunMountCapturesMountLog verifies that when the daemon fails to mount,
// runMount has created <daemonDir>/mount.log before spawning the daemon and
// the parent's failure message points at both fusey.log and mount.log.
//
// The test invokes `go run` on this package's source main() — NOT the test
// binary. Re-execing the test binary via os.Executable() does not work: a
// `go test` binary has its main() replaced by testing.Main(), so it would
// run all tests (including this one) in the subprocess, causing infinite
// recursion. Using `go run` on the source directory gives us a real fusey
// binary whose main() dispatches to runMount based on os.Args[1].
//
// Skips when /dev/fuse is not available or when `go` is not in PATH,
// matching the patterns used in internal/fuse/fs_test.go and the CI runner.
func TestRunMountCapturesMountLog(t *testing.T) {
	if _, err := os.Stat("/dev/fuse"); err != nil {
		t.Skipf("/dev/fuse not available: %v", err)
	}
	if _, err := exec.LookPath("go"); err != nil {
		t.Skipf("go not in PATH: %v", err)
	}

	cacheDir := t.TempDir()

	// The test file lives in cmd/fusey/, which is the package we want
	// `go run` to compile. runtime.Caller(0) gives us this path reliably
	// regardless of where the test is invoked from.
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller(0) failed")
	}
	cmdFuseyDir := filepath.Dir(thisFile)

	// A mountpoint under our temp dir that does not exist (and is not created
	// in any setup step). gofs.Mount will fail on it — either in mountDirect
	// (syscall.Stat returns ENOENT) or in the callFusermount fallback.
	badMount := filepath.Join(cacheDir, "does-not-exist")

	// Run the source, not the test binary. We invoke go run with the absolute
	// package directory so this works regardless of working directory.
	cmd := exec.Command("go", "run", cmdFuseyDir, "mount", badMount)
	cmd.Env = append(os.Environ(), "FUSEY_CACHE_DIR="+cacheDir)
	out, err := cmd.CombinedOutput()
	if err == nil {
		t.Fatalf("expected fusey mount to fail; output:\n%s", out)
	}

	outStr := string(out)

	// The parent's failure message must mention both log files so the user
	// knows where to look. This is the user-facing half of the fix.
	if !strings.Contains(outStr, "mount.log") {
		t.Errorf("expected failure message to mention mount.log; got:\n%s", outStr)
	}
	if !strings.Contains(outStr, "fusey.log") {
		t.Errorf("expected failure message to mention fusey.log; got:\n%s", outStr)
	}

	// runMount must have created <daemonDir>/mount.log inside the cache dir.
	// The daemon ID is random, so we look for any daemonDir/mount.log pair.
	mountLog, err := findMountLog(cacheDir)
	if err != nil {
		t.Fatalf("mount.log not found under %s: %v; output:\n%s", cacheDir, err, out)
	}

	// mount.log should exist and be a regular file. We don't assert non-empty
	// because the daemon's stderr could legitimately be empty in some failure
	// modes (e.g. gofs.Mount returns before any helper writes to fd 2).
	info, err := os.Stat(mountLog)
	if err != nil {
		t.Fatal(err)
	}
	if !info.Mode().IsRegular() {
		t.Errorf("mount.log is not a regular file: mode=%v", info.Mode())
	}
}

// findMountLog searches cacheDir for <some-daemon-dir>/mount.log. The daemon ID
// is generated by newDaemonID() so we don't know it up front; we just need to
// find the file that runMount left behind.
func findMountLog(cacheDir string) (string, error) {
	entries, err := os.ReadDir(cacheDir)
	if err != nil {
		return "", err
	}
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		candidate := filepath.Join(cacheDir, e.Name(), "mount.log")
		if info, err := os.Stat(candidate); err == nil && info.Mode().IsRegular() {
			return candidate, nil
		}
	}
	return "", &os.PathError{Op: "find", Path: cacheDir, Err: os.ErrNotExist}
}
