//go:build linux

package main

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// TestRunMountCapturesMountLog verifies that when the daemon fails to mount,
// runMount has created <daemonDir>/mount.log before spawning the daemon and
// the parent's failure message points at both fusey.log and mount.log.
//
// The test re-execs the test binary as `fusey mount <bad-mountpoint>` so that
// the production runMount() runs end-to-end (no mocks). We use a non-existent
// mountpoint to reliably fail gofs.Mount, and we skip entirely on systems
// where /dev/fuse is not available, matching the pattern used by
// internal/fuse/fs_test.go.
func TestRunMountCapturesMountLog(t *testing.T) {
	if _, err := os.Stat("/dev/fuse"); err != nil {
		t.Skipf("/dev/fuse not available: %v", err)
	}

	cacheDir := t.TempDir()
	exe, err := os.Executable()
	if err != nil {
		t.Fatal(err)
	}

	// A mountpoint under our temp dir that does not exist (and is not created
	// in any setup step). gofs.Mount will fail on it — either in mountDirect
	// (syscall.Stat returns ENOENT) or in the callFusermount fallback.
	badMount := filepath.Join(cacheDir, "does-not-exist")

	cmd := exec.Command(exe, "mount", badMount)
	cmd.Env = append(os.Environ(), "FUSEY_CACHE_DIR="+cacheDir)
	out, err := cmd.CombinedOutput()
	if err == nil {
		t.Fatalf("expected fusey mount to fail; output:\n%s", out)
	}

	outStr := string(out)

	// The parent's failure message must mention both log files so the user
	// knows where to look. This is the user-facing half of the fix.
	if !strings.Contains(outStr, "mount.log") {
		t.Errorf("expected failure message to mention mount.log; got:\n%s", outStr)
	}
	if !strings.Contains(outStr, "fusey.log") {
		t.Errorf("expected failure message to mention fusey.log; got:\n%s", outStr)
	}

	// runMount must have created <daemonDir>/mount.log inside the cache dir.
	// The daemon ID is random, so we look for any daemonDir/mount.log pair.
	mountLog, err := findMountLog(cacheDir)
	if err != nil {
		t.Fatalf("mount.log not found under %s: %v; output:\n%s", cacheDir, err, out)
	}

	// mount.log should exist and be a regular file. We don't assert non-empty
	// because the daemon's stderr could legitimately be empty in some failure
	// modes (e.g. gofs.Mount returns before any helper writes to fd 2).
	info, err := os.Stat(mountLog)
	if err != nil {
		t.Fatal(err)
	}
	if !info.Mode().IsRegular() {
		t.Errorf("mount.log is not a regular file: mode=%v", info.Mode())
	}
}

// findMountLog searches cacheDir for <some-daemon-dir>/mount.log. The daemon ID
// is generated by newDaemonID() so we don't know it up front; we just need to
// find the file that runMount left behind.
func findMountLog(cacheDir string) (string, error) {
	entries, err := os.ReadDir(cacheDir)
	if err != nil {
		return "", err
	}
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		candidate := filepath.Join(cacheDir, e.Name(), "mount.log")
		if info, err := os.Stat(candidate); err == nil && info.Mode().IsRegular() {
			return candidate, nil
		}
	}
	return "", &os.PathError{Op: "find", Path: cacheDir, Err: os.ErrNotExist}
}
